# Generated by Django 2.2.5 on 2020-04-21 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solaranalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day_production', models.CharField(max_length=3000)),
                ('current_day_usage', models.CharField(max_length=300)),
                ('weekly_day_production', models.CharField(max_length=3000)),
                ('weekly_day_usage', models.CharField(max_length=3000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
